name: condominio_roles
description: App Flutter de condominios con UI condicional por rol (ADMIN, RESIDENTE, GUARDIA)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.0
  share_plus: ^10.1.2
  postgres: ^3.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.9.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - .env
